services:
  postgres:
    container_name: dd-mm-pg
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - .././Microservices/AuthService/sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - .././Microservices/AuthService/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - .././Microservices/AuthService/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - .././Microservices/MobService/sql/databases.sql:/docker-entrypoint-initdb.d/4.databases.sql
      - .././Microservices/MobService/sql/schema.sql:/docker-entrypoint-initdb.d/5.schema.sql
      - .././Microservices/MobService/sql/data.sql:/docker-entrypoint-initdb.d/6.data.sql
