import type { Metadata } from "next";
import ThemeWrapper from "../components/ThemeWrapper";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme')?.value ?? 'light';
  return (
    <html lang="en">
      <body>
        <ThemeWrapper initialTheme = {themeCookie}>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
